In [1]:
import sys
import os

# Get the absolute path to the parent directory containing "02504 Computer Vision"
parent_dir = os.path.abspath(os.path.join("../../..", "02504-Computer-Vision"))

# Add it to sys.path
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from utility import Pi, Piinv, projectpoints, point_line_distance, projection_matrix

In [2]:
import numpy as np
import cv2

![explain](images/explanation2.png)

![q1](images/q1.png)

In [3]:
q = np.asarray([2, 4, 3])
l = np.asarray([1, 2, 2])
d = np.linalg.norm(l.T @ q) / (np.linalg.norm(q[-1]) * np.sqrt(l[0]**2.0 + l[1]**2.0))
d

np.float64(2.3851391759997758)

In [4]:
q_new = np.expand_dims(q, axis=1)
l_new = np.expand_dims(l, axis=1)
q_new.shape
point_line_distance(l_new, q_new)

array([[2.38513918]])

![q2](images/q2.png)

![explain](images/explanation.png)

In [5]:
f = 1720
point = (680, 610)
cx = point[0]
cy = point[1]
K = np.asarray([[f, 0, cx], [0, f, cy], [0, 0, 1]])
rvec = np.array([-0.1, 0.1, -0.2])
rot_matrix = cv2.Rodrigues(rvec)[0]
t = np.array([[0.09], [0.05], [0.05]])
extrinsics = np.concatenate((rot_matrix, t), axis=1)
K.shape, extrinsics.shape, extrinsics

((3, 3),
 (3, 4),
 array([[ 0.97512475,  0.19303094,  0.1089531 ,  0.09      ],
        [-0.20298104,  0.97512475,  0.0890529 ,  0.05      ],
        [-0.0890529 , -0.1089531 ,  0.9900499 ,  0.05      ]]))

In [9]:
P = projection_matrix(K, rot_matrix, t)
P

array([[ 1.61665860e+03,  2.57925114e+02,  8.60633257e+02,
         1.88800007e+02],
       [-4.03449658e+02,  1.61075318e+03,  7.57101420e+02,
         1.16500002e+02],
       [-8.90528958e-02, -1.08953096e-01,  9.90049900e-01,
         5.00000007e-02]])

In [7]:
Q_homo = Piinv(np.array([-0.03, 0.01, 0.59]).reshape(3, 1))
homo_2d = projectpoints(K, rot_matrix, t, Q_homo)
Pi(homo_2d)

array([[1023.50377104],
       [ 930.29756751]])

## Alternative:

In [14]:
K = np.float32(K)
rvec = np.float32(rvec)
t = np.float32(t)
Q = Q = np.float32(np.array([-0.03, 0.01, 0.59]).reshape(3, 1))
dist_coeffs = np.zeros((5, 1), np.float32)
points , _ = cv2.projectPoints(Q, rvec, t, K, dist_coeffs)
points

array([[[1023.5038,  930.2976]]], dtype=float32)